require 'kickstart.plugins.git'
require 'kickstart.plugins.colorscheme'
require 'kickstart.plugins.mini'
require 'kickstart.plugins.telescope'
require 'kickstart.plugins.files'
require 'kickstart.plugins.lspconfig'
require 'kickstart.plugins.conform'
require 'kickstart.plugins.snippet'
require 'kickstart.plugins.autopairs'
require 'kickstart.plugins.indent'
-- require 'kickstart.plugins.debug'
-- require 'kickstart.plugins.indent_line'
-- require 'kickstart.plugins.lint'

require 'custom.plugins'
